// <auto-generated />
using System;
using LoginApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113162847_AddBanconoteWithdrawalAutomaticTable")]
    partial class AddBanconoteWithdrawalAutomaticTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LoginApi.Models.BanconoteWithdrawalAutomatic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CountingAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_amount");

                    b.Property<DateTime?>("CountingAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_at");

                    b.Property<string>("CountingBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_by");

                    b.Property<decimal?>("CountingCoins")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_coins");

                    b.Property<DateTime?>("CountingCourierDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_courier_date");

                    b.Property<DateTime?>("CountingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_date");

                    b.Property<decimal?>("CountingDifference")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_difference");

                    b.Property<string>("CountingTime")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_time");

                    b.Property<int>("IdStore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_store");

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("import_date");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("SecurityEnvelopeCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_envelope_code");

                    b.Property<string>("StoreAlias")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("store_alias");

                    b.Property<decimal?>("Totale")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totale");

                    b.Property<string>("User")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user");

                    b.Property<DateTime?>("WithdrawalDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("withdrawal_date");

                    b.HasKey("Id");

                    b.ToTable("BanconoteWithdrawalAutomatic");
                });

            modelBuilder.Entity("LoginApi.Models.Busta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataChiusura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRiferimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRitiro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigillo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Totale")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserChiusura")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserRitiro")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Buste");
                });

            modelBuilder.Entity("LoginApi.Models.CashFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CashCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_code");

                    b.Property<string>("Cassa")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("cassa");

                    b.Property<decimal?>("CountingAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_amount");

                    b.Property<DateTime?>("CountingAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_at");

                    b.Property<string>("CountingBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_by");

                    b.Property<decimal?>("CountingCoins")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_coins");

                    b.Property<DateTime?>("CountingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_date");

                    b.Property<string>("CountingTime")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_time");

                    b.Property<int>("IdStore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_store");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Totale")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totale");

                    b.Property<string>("User")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.ToTable("CashFund");
                });

            modelBuilder.Entity("LoginApi.Models.ExpenseFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CountingAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_amount");

                    b.Property<DateTime?>("CountingAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_at");

                    b.Property<string>("CountingBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_by");

                    b.Property<decimal?>("CountingCoins")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_coins");

                    b.Property<DateTime?>("CountingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_date");

                    b.Property<string>("CountingTime")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_time");

                    b.Property<string>("ExpenseType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("expense_type");

                    b.Property<string>("Fattura")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("fattura");

                    b.Property<string>("Fornitore")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("fornitore");

                    b.Property<int>("IdStore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_store");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("ReasonExpenses")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason_expenses");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<decimal?>("Totale")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totale");

                    b.Property<string>("User")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.ToTable("ExpenseFund");
                });

            modelBuilder.Entity("LoginApi.Models.MonetaryFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CountingAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_amount");

                    b.Property<DateTime?>("CountingAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_at");

                    b.Property<string>("CountingBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_by");

                    b.Property<decimal?>("CountingCoins")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("counting_coins");

                    b.Property<DateTime?>("CountingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_date");

                    b.Property<string>("CountingNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_note");

                    b.Property<string>("CountingTime")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("counting_time");

                    b.Property<int>("IdStore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_store");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<decimal?>("Totale")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totale");

                    b.Property<decimal?>("TotaleBanconote")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totale_banconote");

                    b.Property<decimal?>("TotaleMonete")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totale_monete");

                    b.Property<string>("User")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.ToTable("MonetaryFund");
                });

            modelBuilder.Entity("LoginApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LoginApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoginApi.Models.Busta", b =>
                {
                    b.HasOne("LoginApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoginApi.Models.RefreshToken", b =>
                {
                    b.HasOne("LoginApi.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoginApi.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
